###
GET https://apihotel02.herokuapp.com/hotel/users HTTP/1.1

###
GET https://apihotel02.herokuapp.com/hotel/admin HTTP/1.1

###

POST https://apihotel02.herokuapp.com/hotel HTTP/1.1
Content-Type: application/json

{
    "regNo":"1233333",
    "firstName":"Pepito",
    "middleName":"Ganzales",
    "lastName":"Gonazales",
    "gender":"male",
    "contactNo":"31145252",
    "email":"pgg@gmail.com",
    "password":"pgg",
    "regDate":"2019-12-13 09:00:24",
    "updationDate":"",
    "passUdateDate":""
}

###
DELETE http://localhost:9000/api/25 HTTP/1.1

###
PUT https://apihotel02.herokuapp.com/hotel/24 HTTP/1.1
Content-Type: application/json

{
    "regNo":"123456",
    "firstName":"Andres",
    "middleName":"Hernando",
    "lastName":"Perez",
    "gender":"male",
    "contactNo":"311442282",
    "email":"fer@gmail.com",
    "password":"123456",
    "regDate":"2019-12-13 09:00:24"
}
###
POST https://apihotel02.herokuapp.com/hotel/prueba HTTP/1.1
Content-Type: application/json

{
    "username":"adminUno",
    "email":"ad@gmail.com",
    "password":"admin",
    "reg_date":"2019-12-13 09:00:24",
    "updation_date":""
}